INSERT INTO Contact_Information (Student_Email,
    Student_Email_2,
    Phone_Number,
    School_Name_1,
    School_Name_2,
    Emergency_Contact_Name_1,
    Emergency_Contact_Number_1,
    Emergency_Contact_Email_1,
    Emergency_Contact_Name_2,
    Emergency_Contact_Number_2,
    Emergency_Contact_Email_2,
    Student_ID) VALUES ('bob@mylaurier.ca', 'bob@uwaterloo.ca', 0000000001, 'Laurier', 'UWaterloo', 'first1', 'last1', 1, 'first2', 'last2', 2, 001);
INSERT INTO Contact_Information (Student_Email,
    Student_Email_2,
    Phone_Number,
    School_Name_1,
    School_Name_2,
    Emergency_Contact_Name_1,
    Emergency_Contact_Number_1,
    Emergency_Contact_Email_1,
    Emergency_Contact_Name_2,
    Emergency_Contact_Number_2,
    Emergency_Contact_Email_2,
    Student_ID) VALUES ('alice@mylaurier.ca', 'none', 0000000002, 'Laurier', 'none', 'first3', 'last3', 3, 'first4', 'last4', 4, 002);
INSERT INTO Contact_Information (Student_Email,
    Student_Email_2,
    Phone_Number,
    School_Name_1,
    School_Name_2,
    Emergency_Contact_Name_1,
    Emergency_Contact_Number_1,
    Emergency_Contact_Email_1,
    Emergency_Contact_Name_2,
    Emergency_Contact_Number_2,
    Emergency_Contact_Email_2,
    Student_ID) VALUES ('dani@mylaurier.ca', 'none', 0000000003, 'Laurier', 'none', 'first5', 'last5', 5, 'first6', 'last6', 6, 003);
INSERT INTO Contact_Information (Student_Email,
    Student_Email_2,
    Phone_Number,
    School_Name_1,
    School_Name_2,
    Emergency_Contact_Name_1,
    Emergency_Contact_Number_1,
    Emergency_Contact_Email_1,
    Emergency_Contact_Name_2,
    Emergency_Contact_Number_2,
    Emergency_Contact_Email_2,
    Student_ID) VALUES ('charlie@mylaurier.ca', 'charlie@uwaterloo.ca', 0000000004, 'Laurier', 'UWaterloo', 'first7', 'last7', 7, 'first8', 'last8', 8, 004);
INSERT INTO Contact_Information (Student_Email,
    Student_Email_2,
    Phone_Number,
    School_Name_1,
    School_Name_2,
    Emergency_Contact_Name_1,
    Emergency_Contact_Number_1,
    Emergency_Contact_Email_1,
    Emergency_Contact_Name_2,
    Emergency_Contact_Number_2,
    Emergency_Contact_Email_2,
    Student_ID) VALUES ('delta@mylaurier.ca', 'delta@uwaterloo.ca', 0000000005, 'Laurier', 'UWaterloo', 'first9', 'last9', 9, 'first10', 'last10', 10, 005);
INSERT INTO Contact_Information (Student_Email,
    Student_Email_2,
    Phone_Number,
    School_Name_1,
    School_Name_2,
    Emergency_Contact_Name_1,
    Emergency_Contact_Number_1,
    Emergency_Contact_Email_1,
    Emergency_Contact_Name_2,
    Emergency_Contact_Number_2,
    Emergency_Contact_Email_2,
    Student_ID) VALUES ('edward@mylaurier.ca', 'none', 0000000006, 'Laurier', 'none', 'first11', 'last11', 11, 'first12', 'last12', 12, 006);
INSERT INTO Contact_Information (Student_Email,
    Student_Email_2,
    Phone_Number,
    School_Name_1,
    School_Name_2,
    Emergency_Contact_Name_1,
    Emergency_Contact_Number_1,
    Emergency_Contact_Email_1,
    Emergency_Contact_Name_2,
    Emergency_Contact_Number_2,
    Emergency_Contact_Email_2,
    Student_ID) VALUES ('riley@mylaurier.ca', 'none', 0000000007, 'Laurier', 'none', 'first13', 'last13', 13, 'first14', 'last14', 14, 007);
INSERT INTO Contact_Information (Student_Email,
    Student_Email_2,
    Phone_Number,
    School_Name_1,
    School_Name_2,
    Emergency_Contact_Name_1,
    Emergency_Contact_Number_1,
    Emergency_Contact_Email_1,
    Emergency_Contact_Name_2,
    Emergency_Contact_Number_2,
    Emergency_Contact_Email_2,
    Student_ID) VALUES ('john@mylaurier.ca', 'john@uwaterloo.ca', 0000000008, 'Laurier', 'UWaterloo', 'first15', 'last15', 15, 'first16', 'last16', 16, 008);
INSERT INTO Contact_Information (Student_Email,
    Student_Email_2,
    Phone_Number,
    School_Name_1,
    School_Name_2,
    Emergency_Contact_Name_1,
    Emergency_Contact_Number_1,
    Emergency_Contact_Email_1,
    Emergency_Contact_Name_2,
    Emergency_Contact_Number_2,
    Emergency_Contact_Email_2,
    Student_ID) VALUES ('jane@mylaurier.ca', 'none', 0000000009, 'Laurier', 'none', 'first17', 'last17', 17, 'first18', 'last18', 18, 009);
INSERT INTO Contact_Information (Student_Email,
    Student_Email_2,
    Phone_Number,
    School_Name_1,
    School_Name_2,
    Emergency_Contact_Name_1,
    Emergency_Contact_Number_1,
    Emergency_Contact_Email_1,
    Emergency_Contact_Name_2,
    Emergency_Contact_Number_2,
    Emergency_Contact_Email_2,
    Student_ID) VALUES ('clifford@mylaurier.ca', 'clifford@uwaterloo.ca', 0000000010, 'Laurier', 'UWaterloo', 'first19', 'last19', 19, 'first20', 'last20', 20, 010);