INSERT INTO Course (Course_Code, 
    Course_Name, 
    Semester, 
    Instructor_Name, 
    Midterm_1_Grade, 
    Midterm_2_Grade, 
    Project_Grade, 
    Final_Exam_Grade, 
    Final_Grade, 
    Completion_Status) VALUES ('CP104', 'Introduction to Programming', 'Fall 2022', 'Dr. Safah Bedawi', 90.00, NULL, NULL, 83.00, 86.00, TRUE);
INSERT INTO Course (Course_Code, 
    Course_Name, 
    Semester, 
    Instructor_Name, 
    Midterm_1_Grade, 
    Midterm_2_Grade, 
    Project_Grade, 
    Final_Exam_Grade, 
    Final_Grade, 
    Completion_Status) VALUES ('CP164', 'Data Structures I', 'Fall 2022', 'Mr. David Brown', 68.00, NULL, 84.00, 59.00, 77.00, TRUE); 
INSERT INTO Course (Course_Code, 
    Course_Name, 
    Semester, 
    Instructor_Name, 
    Midterm_1_Grade, 
    Midterm_2_Grade, 
    Project_Grade, 
    Final_Exam_Grade, 
    Final_Grade, 
    Completion_Status) VALUES ('ES110', 'Environmental Studies', 'Fall 2022', 'Dr. Robert Mcleman', 90.00, 82.00, NULL, 86.00, 85.00, TRUE);
INSERT INTO Course (Course_Code, 
    Course_Name, 
    Semester, 
    Instructor_Name, 
    Midterm_1_Grade, 
    Midterm_2_Grade, 
    Project_Grade, 
    Final_Exam_Grade, 
    Final_Grade, 
    Completion_Status) VALUES ('DATA100', 'Data Analysis', 'Fall 2022', 'Dr. Shengda Hu', 62.00, NULL, 71.00, 64.00, 68.00, TRUE);
INSERT INTO Course (Course_Code, 
    Course_Name, 
    Semester, 
    Instructor_Name, 
    Midterm_1_Grade, 
    Midterm_2_Grade, 
    Project_Grade, 
    Final_Exam_Grade, 
    Final_Grade, 
    Completion_Status) VALUES ('MA103', 'Calculus I', 'Fall 2022', 'Dr. Fei Xu', 77.00, 66.00, NULL, 61.00, 65.00, TRUE);
INSERT INTO Course (Course_Code, 
    Course_Name, 
    Semester, 
    Instructor_Name, 
    Midterm_1_Grade, 
    Midterm_2_Grade, 
    Project_Grade, 
    Final_Exam_Grade, 
    Final_Grade, 
    Completion_Status) VALUES ('UU100', 'Mental Health', 'Winter 2023', 'Dr. Susan Cole', NULL, NULL, NULL, 0.00, NULL, FALSE);
INSERT INTO Course (Course_Code, 
    Course_Name, 
    Semester, 
    Instructor_Name, 
    Midterm_1_Grade, 
    Midterm_2_Grade, 
    Project_Grade, 
    Final_Exam_Grade, 
    Final_Grade, 
    Completion_Status) VALUES ('MA120', 'Discrete Structures', 'Winter 2023', 'Dr. Robert Rundle', NULL, NULL, NULL, 0.00, NULL, FALSE);
INSERT INTO Course (Course_Code, 
    Course_Name, 
    Semester, 
    Instructor_Name, 
    Midterm_1_Grade, 
    Midterm_2_Grade, 
    Project_Grade, 
    Final_Exam_Grade, 
    Final_Grade, 
    Completion_Status) VALUES ('MA170', 'Mathematics for Finance', 'Winter 2023', 'Mr. Andrew Kabbes', NULL, NULL, NULL, 0.00, NULL, FALSE);
INSERT INTO Course (Course_Code, 
    Course_Name, 
    Semester, 
    Instructor_Name, 
    Midterm_1_Grade, 
    Midterm_2_Grade, 
    Project_Grade, 
    Final_Exam_Grade, 
    Final_Grade, 
    Completion_Status) VALUES ('UU101', 'Sustainability', 'Winter 2023', 'Dr. Livia Dittmer', NULL, NULL, NULL, 0.00, NULL, FALSE);
INSERT INTO Course (Course_Code, 
    Course_Name, 
    Semester, 
    Instructor_Name, 
    Midterm_1_Grade, 
    Midterm_2_Grade, 
    Project_Grade, 
    Final_Exam_Grade, 
    Final_Grade, 
    Completion_Status) VALUES ('GG101', 'Geology', 'Winter 2023', 'Dr. Michael Bitton', NULL, NULL, NULL, 0.00, NULL, FALSE);